# Generated by Django 5.2.17 on 2026-09-17 03:49

import usuarios.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.managers.UsuarioManager()),
            ],
        ),
    ]
