# Generated by Django 5.2.17 on 2026-10-04 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_crear_roles_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('DESBLOQUEO_USUARIO', 'Desbloqueo de usuario'), ('REINICIO_INTENTOS', 'Reinicio de intentos'), ('BLOQUEO_USUARIO', 'Bloqueo de usuario'), ('OTRO', 'Otra acción de seguridad')], max_length=50)),
                ('email_afectado', models.EmailField(max_length=254)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_seguridad_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de seguridad',
                'verbose_name_plural': 'Historial de seguridad',
                'ordering': ['-fecha'],
            },
        ),
    ]
