"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'axes',

    "organizacion",
    "usuarios",
    "requerimientos",
    "core",
    "inventario",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "axes.middleware.AxesMiddleware",
    "core.middleware.SessionExpiredMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ["DB_NAME"],
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PASSWORD"],
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "usuarios.Usuario"

LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"

USE_I18N = True
USE_TZ = True

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"


AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# ==========================================================
# SEGURIDAD DE INICIO DE SESIÓN - DJANGO AXES
# ==========================================================

# Máximo de intentos fallidos
AXES_FAILURE_LIMIT = 2

# Bloqueo temporal de 15 minutos
AXES_COOLOFF_TIME = timedelta(minutes=1)

# Reiniciar contador después de un login correcto
AXES_RESET_ON_SUCCESS = True

# Nuestro usuario se identifica mediante email
AXES_USERNAME_FORM_FIELD = "username"

# Bloquear por usuario/correo y no por IP
AXES_LOCKOUT_PARAMETERS = ["username"]

# Ventana móvil para los intentos
AXES_USE_ATTEMPT_EXPIRATION = True

# Informar al cliente cuánto dura el bloqueo
AXES_ENABLE_RETRY_AFTER_HEADER = True
# Página personalizada cuando la cuenta queda bloqueada
AXES_LOCKOUT_TEMPLATE = "registration/locked_out.html"


# ==========================================================
# SEGURIDAD DE SESIONES
# ==========================================================

# 30 minutos
#SESSION_COOKIE_AGE = max_age=(30 * 60) + 300,

#pruebas de 1 minuto
SESSION_COOKIE_AGE = max_age=60

# Renovar la expiración con cada solicitud del usuario.
# Mientras siga utilizando el sistema, la sesión continúa activa.
SESSION_SAVE_EVERY_REQUEST = True

# Si el navegador se cierra, finalizar la sesión.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# La cookie de sesión no puede ser leída desde JavaScript.
# SESSION_COOKIE_HTTPONLY = True

# # SameSite ayuda frente a solicitudes entre sitios.
# SESSION_COOKIE_SAMESITE = "Lax"