# Generated by Django 5.2.17 on 2026-09-17 04:02
from django.db import migrations


def cargar_datos(apps, schema_editor):
    Estado = apps.get_model("requerimientos", "EstadoRequerimiento")
    Prioridad = apps.get_model("requerimientos", "Prioridad")
    Tipo = apps.get_model("requerimientos", "TipoRequerimiento")

    estados = [
        ("Pendiente", "Requerimiento ingresado y pendiente de asignación."),
        ("Asignado", "Requerimiento asignado a un Técnico TI."),
        ("En proceso", "Requerimiento actualmente en atención."),
        ("Resuelto", "La solución fue registrada por el Técnico TI."),
        ("Cerrado", "Requerimiento finalizado."),
        ("Cancelado", "Requerimiento cancelado."),
    ]

    for nombre, descripcion in estados:
        Estado.objects.get_or_create(
            nombre=nombre,
            defaults={"descripcion": descripcion},
        )

    prioridades = [
        ("Baja", 1),
        ("Media", 2),
        ("Alta", 3),
        ("Crítica", 4),
    ]

    for nombre, nivel in prioridades:
        Prioridad.objects.get_or_create(
            nombre=nombre,
            defaults={"nivel": nivel},
        )

    tipos = [
        "Hardware",
        "Software",
        "Red y conectividad",
        "Impresoras",
        "Cuenta de usuario",
        "Instalación",
        "Mantención",
        "Otro",
    ]

    for nombre in tipos:
        Tipo.objects.get_or_create(nombre=nombre)


def eliminar_datos(apps, schema_editor):
    Estado = apps.get_model("requerimientos", "EstadoRequerimiento")
    Prioridad = apps.get_model("requerimientos", "Prioridad")
    Tipo = apps.get_model("requerimientos", "TipoRequerimiento")

    Estado.objects.filter(
        nombre__in=[
            "Pendiente",
            "Asignado",
            "En proceso",
            "Resuelto",
            "Cerrado",
            "Cancelado",
        ]
    ).delete()

    Prioridad.objects.filter(
        nombre__in=["Baja", "Media", "Alta", "Crítica"]
    ).delete()

    Tipo.objects.filter(
        nombre__in=[
            "Hardware",
            "Software",
            "Red y conectividad",
            "Impresoras",
            "Cuenta de usuario",
            "Instalación",
            "Mantención",
            "Otro",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("requerimientos", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            cargar_datos,
            eliminar_datos,
        ),
    ]